# This triggers on all PRs to validate the change using Terraform Plan

name: Pull Request - Validate

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:
    
concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  dev:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "[DEV]"
    uses: faccomichele-org/gha-reusables/.github/workflows/terraform-run.yml@main
    with:
      environment: 'dev'
      region: 'eu-central-1'
      global: true
      working-directory: '.'
      action: 'plan'
    secrets: inherit
